### ISSUE TITLE
Suggestion: Keep chapters' format in linear order

### ISSUE THREAD

**Issue by stefanos82** [xmonader/nimdays#1]
As we can see from the screenshot, the chapters are not in linear order.

![image](https://user-images.githubusercontent.com/1777466/43370930-9095f648-9390-11e8-9327-594a1298b4f6.png)

I have had this issue myself with LaTeX and the easiest way to fix it is by prefixing it with leading zeroes.

```txt
days01...
days02...
days03...
...
days10...
```
This way it respects the linear order should follow.

**Comment by xmonader** [comment]
I fixed that :)
