### ISSUE TITLE
tcp router question

### ISSUE THREAD

**Issue by geohuz** [xmonader/nimdays#10]
I saw the Forwarder is defined like this:

```
type Forwarder = object of RootObj
  options*: ForwardOptions
```

and then there is a constructor proc:

```
proc newForwarder(opts: ForwardOptions):  ref Forwarder =
  result = new(Forwarder) 
  result.options = opts
```

and then Forwarder can be passed into processClient and serve with type ```ref Forwarder```

and as I'm quite new to nim, I was confused with defining Fowarder in ref object, and the whole code like this:
```
type Forwarder = ref object of RootObj  
  options*: ForwardOptions
.
.
proc newForwarder(opts: ForwardOptions): Forwarder =
  result = new(Forwarder) 
  result.options = opts
.
.
proc serve(this: Forwarder) {.async.} =
...
```

the code is ok to be compiled, but I don't know if it's ok to do that, and the difference between the two way of defining object.

**Comment by geohuz** [comment]
I guess the ``ref object of RootObj`` is for object inheritance,  so ``object of RootObj`` is merely means we don't want any inheritance here, is that true? Or there is any other purpose behind scene?

**Comment by xmonader** [comment]
Hi sorry for the confusion

I quickly went through the code
```nim
type ForwardOptions = object
  listenAddr*: string
  listenPort*: Port
  toAddr*: string
  toPort*: Port

type Forwarder = object of RootObj
  options*: ForwardOptions


proc newForwarder(opts: ForwardOptions): ref Forwarder =
  result = new(Forwarder)
  result.options = opts
```

- value types are `type MyClass = object ..` (allocated on the stack) "can be immutable when initialized with `let` construct`
- ref types are `type MyClass = ref object`   (allocated on the heap)

- there is `initXXX` function to create that object on the stack
- there is `newXXX` function to create the object on the heap 
- lots of times you will types like `Table[X,Y] and TableRef[X,Y]` basically the same but where the object are stored.


RootObj is only used if you want to enable inheritance, and yes It's not used just how I type and autocomplete code. I'll revise and remove what is not needed.

**Comment by geohuz** [comment]
Thanks for the explanation, now I that made clear!
