### ISSUE TITLE
Document mdbook dependency

### ISSUE THREAD

**Issue by epogrebnyak** [xmonader/nimdays#15]
Publish.sh uses mdbook, assumes it is installed at PATH. I think it needs a mention in Readme or in script comment, what do you think? 

Is this a correct link? 

https://github.com/rust-lang/mdBook

**Comment by xmonader** [comment]
Added here https://github.com/xmonader/nimdays/commit/edc1ff3c9f042f83cf68f5d989e50a7b3a49556c thank you :)

**Comment by epogrebnyak** [comment]
Thank you for a quick update!

**Comment by xmonader** [comment]
you're very welcome :)
