### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by s0kil** [xmonader/nimdays#2]
Any reason you don't write tests?

**Comment by xmonader** [comment]
That's a very good question, I totally should include tests with each chapter with the right balance between reasonable tests and not overwhelming the reader with so many testing terminology. Maybe it can be extra optional section in each chapter, but that would send the wrong message about TDD? What do you think?

I only created tests for bencode chapter https://github.com/xmonader/nim-bencode/blob/master/tests/test1.nim

and here's one I'm planning to port from dmiparse python library
https://github.com/xmonader/dmiparse/blob/master/tests/test_dmiparse.py

And your help is also very much appreciated ^_^

**Comment by DanielSokil** [comment]
Test for chapter 7 would be amazing.
I will try to contribute as Nim becomes more familiar.
