### ISSUE TITLE
Very new person, can't get first code to compile

### ISSUE THREAD

**Issue by symgryph** [xmonader/nimdays#7]
I did try almost all of the examples, and none would compile. I was wondering for 'finalized' source code so I can see what I am doing wrong. I also did try the 'shorturl' program, (created a new NIM file) then created shorturl.c in a directory, then 'nim c' and only found that I got :

Hint: used config file '/usr/local/Cellar/nim/1.0.0/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: shorturl [Processing]
/Users/tmunn/src/nim/shorturl/shorturl.nim(4, 8) Error: cannot open file: jester

**Comment by xmonader** [comment]
Hello! Thanks for checking out Nim Days! Apparently you don't have jester installed. `nimble install jester` would fix it I'll update the chapter with that note. Sorry for the inconvenience

Here's the complete code 
https://gist.github.com/xmonader/d41a5c9f917eadb90d3025e7b7e748dd

**Comment by symgryph** [comment]
Got farther:  

Users/tmunn/src/nim/shorturl/test.nim(9, 15) Error: type mismatch: got <string, typeof(nil), typeof(nil), typeof(nil)>
but expected one of: 
proc open(filename: string; mode: FileMode = fmRead; bufSize: int = -1): File
  first type mismatch at position: 2
  required type for mode: FileMode
  but expression 'nil' is of type: typeof(nil)
proc open(connection, user, password, database: string): DbConn
  first type mismatch at position: 2
  required type for user: string
  but expression 'nil' is of type: typeof(nil)
4 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: open("/Users/tmunn/mytest.db", nil, nil, nil)

**Comment by xmonader** [comment]
Hi I've updated the code. Problem is Nim isn't allowing the value `nil` for sequences anymore, passing empty string instead in the open function
